// IsolatedMicroKernel.cpp - Surgical micro-kernel benchmark
// NO overhead: No allocations, no JIT, pure FMA chain in registers
//
// Goal: 45-50 GFLOPS on 6x16x256 micro-kernel
//
// Register allocation (16 YMM registers):
//   YMM0-YMM11:  12 accumulators (C: 6 rows × 2 vectors of 8 floats)
//   YMM12-YMM13: 2 B vectors (16 floats = 2×8)
//   YMM14:       1 A broadcast register
//   YMM15:       Spare

#include <iostream>
#include <chrono>
#include <cstring>
#include <cstdlib>
#include <immintrin.h>

// ============================================================
// MICRO-KERNEL CONSTANTS
// ============================================================
constexpr int MR = 6;        // Rows (6 = optimal for AVX2)
constexpr int NR = 16;       // Columns (16 = 2 AVX2 vectors)
constexpr int K = 256;       // Depth (fits in L1 cache: 6*256 + 256*16 + 6*16 = ~18KB < 32KB)
constexpr int ITERATIONS = 10000000;  // 10M runs for stable measurement
constexpr int WARMUP_ITERATIONS = 100000;  // 100K warmup runs

// ============================================================
// EXTERNAL FUNCTION - Generated by MLIR, linked from micro_kernel.o
// ============================================================
// This function is exported as C ABI from MLIR-compiled code
// Signature: void micro_kernel_6x16(float* A, float* B, float* C)
//
// Memory layout expectations:
//   A: [MR x K] row-major   (6 x 256)
//   B: [K x NR] packed column-major (256 x 16, consecutive column access)
//   C: [MR x NR] row-major (6 x 16)
//
#ifdef HAS_MLIR_KERNEL
extern "C" void micro_kernel_6x16(float* A, float* B, float* C);
#endif

// ============================================================
// REFERENCE IMPLEMENTATION (for validation)
// ============================================================
void reference_matmul_6x16(const float* A, const float* B, float* C) {
    for (int i = 0; i < MR; i++) {
        for (int j = 0; j < NR; j++) {
            float sum = C[i * NR + j];
            for (int k = 0; k < K; k++) {
                sum += A[i * K + k] * B[k * NR + j];
            }
            C[i * NR + j] = sum;
        }
    }
}

// ============================================================
// INTRINSICS-BASED MICRO-KERNEL (Baseline for comparison)
// ============================================================
void intrinsic_microkernel_6x16(const float* __restrict__ A,
                                 const float* __restrict__ B,
                                 float* __restrict__ C) {
    // Load C into 12 YMM registers (6 rows × 2 vectors)
    __m256 c00 = _mm256_load_ps(&C[0 * NR + 0]);
    __m256 c01 = _mm256_load_ps(&C[0 * NR + 8]);
    __m256 c10 = _mm256_load_ps(&C[1 * NR + 0]);
    __m256 c11 = _mm256_load_ps(&C[1 * NR + 8]);
    __m256 c20 = _mm256_load_ps(&C[2 * NR + 0]);
    __m256 c21 = _mm256_load_ps(&C[2 * NR + 8]);
    __m256 c30 = _mm256_load_ps(&C[3 * NR + 0]);
    __m256 c31 = _mm256_load_ps(&C[3 * NR + 8]);
    __m256 c40 = _mm256_load_ps(&C[4 * NR + 0]);
    __m256 c41 = _mm256_load_ps(&C[4 * NR + 8]);
    __m256 c50 = _mm256_load_ps(&C[5 * NR + 0]);
    __m256 c51 = _mm256_load_ps(&C[5 * NR + 8]);

    for (int k = 0; k < K; k++) {
        // Load B[k, 0:16] - 2 vectors
        __m256 b0 = _mm256_load_ps(&B[k * NR + 0]);
        __m256 b1 = _mm256_load_ps(&B[k * NR + 8]);

        // Broadcast A[i, k] and FMA for each row
        __m256 a0 = _mm256_broadcast_ss(&A[0 * K + k]);
        c00 = _mm256_fmadd_ps(a0, b0, c00);
        c01 = _mm256_fmadd_ps(a0, b1, c01);

        __m256 a1 = _mm256_broadcast_ss(&A[1 * K + k]);
        c10 = _mm256_fmadd_ps(a1, b0, c10);
        c11 = _mm256_fmadd_ps(a1, b1, c11);

        __m256 a2 = _mm256_broadcast_ss(&A[2 * K + k]);
        c20 = _mm256_fmadd_ps(a2, b0, c20);
        c21 = _mm256_fmadd_ps(a2, b1, c21);

        __m256 a3 = _mm256_broadcast_ss(&A[3 * K + k]);
        c30 = _mm256_fmadd_ps(a3, b0, c30);
        c31 = _mm256_fmadd_ps(a3, b1, c31);

        __m256 a4 = _mm256_broadcast_ss(&A[4 * K + k]);
        c40 = _mm256_fmadd_ps(a4, b0, c40);
        c41 = _mm256_fmadd_ps(a4, b1, c41);

        __m256 a5 = _mm256_broadcast_ss(&A[5 * K + k]);
        c50 = _mm256_fmadd_ps(a5, b0, c50);
        c51 = _mm256_fmadd_ps(a5, b1, c51);
    }

    // Store C back
    _mm256_store_ps(&C[0 * NR + 0], c00);
    _mm256_store_ps(&C[0 * NR + 8], c01);
    _mm256_store_ps(&C[1 * NR + 0], c10);
    _mm256_store_ps(&C[1 * NR + 8], c11);
    _mm256_store_ps(&C[2 * NR + 0], c20);
    _mm256_store_ps(&C[2 * NR + 8], c21);
    _mm256_store_ps(&C[3 * NR + 0], c30);
    _mm256_store_ps(&C[3 * NR + 8], c31);
    _mm256_store_ps(&C[4 * NR + 0], c40);
    _mm256_store_ps(&C[4 * NR + 8], c41);
    _mm256_store_ps(&C[5 * NR + 0], c50);
    _mm256_store_ps(&C[5 * NR + 8], c51);
}

// ============================================================
// BENCHMARK RUNNER
// ============================================================
template<typename KernelFunc>
double benchmark_kernel(KernelFunc kernel, float* A, float* B, float* C,
                        const char* name, int iterations) {
    // Reset C
    std::memset(C, 0, MR * NR * sizeof(float));

    // Warmup (fill caches, warm up CPU frequency)
    for (int i = 0; i < WARMUP_ITERATIONS; i++) {
        kernel(A, B, C);
    }

    // Reset C after warmup
    std::memset(C, 0, MR * NR * sizeof(float));

    // Benchmark - NOTE: We intentionally don't reset C between iterations
    // because the real micro-kernel is supposed to accumulate into C.
    // The performance measurement is for the FMA throughput, not correctness.
    auto start = std::chrono::high_resolution_clock::now();
    for (int i = 0; i < iterations; i++) {
        kernel(A, B, C);
    }
    auto end = std::chrono::high_resolution_clock::now();

    std::chrono::duration<double> elapsed = end - start;

    // Calculate GFLOPS
    // Operations per kernel call: 2 * MR * NR * K (mul + add per element)
    double ops_per_call = 2.0 * MR * NR * K;
    double total_ops = ops_per_call * iterations;
    double gflops = (total_ops / elapsed.count()) / 1e9;

    std::cout << "  " << name << ":\n";
    std::cout << "    Time: " << elapsed.count() << " s\n";
    std::cout << "    GFLOPS: " << gflops << "\n";

    // Calculate expected value after all iterations
    // Each iteration adds: 1.0 * 0.5 * K = 128
    // After N iterations: 128 * N
    float expected_accumulated = 1.0f * 0.5f * K * (iterations + 1000); // +1000 from warmup that wasn't reset
    std::cout << "    C[0,0] = " << C[0] << " (accumulated over " << iterations << " iterations)\n";

    return gflops;
}

// ============================================================
// MAIN
// ============================================================
int main(int argc, char** argv) {
    std::cout << "\n╔════════════════════════════════════════════════════════╗\n";
    std::cout << "║  🔬 ISOLATED MICRO-KERNEL BENCHMARK                    ║\n";
    std::cout << "║  Pure computational performance (no overhead)          ║\n";
    std::cout << "╠════════════════════════════════════════════════════════╣\n";
    std::cout << "║  Matrix: " << MR << " x " << K << " × " << K << " x " << NR
              << " → " << MR << " x " << NR << "                    ║\n";
    std::cout << "║  Iterations: " << ITERATIONS << " (10M)                     ║\n";
    std::cout << "║  Warmup: " << WARMUP_ITERATIONS << " (100K)                         ║\n";
    std::cout << "║  Target: 45-55 GFLOPS (AVX2 peak: ~60 GFLOPS)          ║\n";
    std::cout << "╚════════════════════════════════════════════════════════╝\n\n";

    // ========================================
    // STEP 1: Allocate aligned memory (32 bytes for AVX2)
    // ========================================
    std::cout << "📦 Allocating aligned memory (32-byte alignment for AVX2)...\n";

    float* A = static_cast<float*>(std::aligned_alloc(32, MR * K * sizeof(float)));
    float* B = static_cast<float*>(std::aligned_alloc(32, K * NR * sizeof(float)));
    float* C = static_cast<float*>(std::aligned_alloc(32, MR * NR * sizeof(float)));
    float* C_ref = static_cast<float*>(std::aligned_alloc(32, MR * NR * sizeof(float)));

    if (!A || !B || !C || !C_ref) {
        std::cerr << "❌ Memory allocation failed!\n";
        return 1;
    }

    std::cout << "  A: " << A << " (" << MR * K * sizeof(float) << " bytes)\n";
    std::cout << "  B: " << B << " (" << K * NR * sizeof(float) << " bytes)\n";
    std::cout << "  C: " << C << " (" << MR * NR * sizeof(float) << " bytes)\n\n";

    // ========================================
    // STEP 2: Initialize matrices
    // ========================================
    std::cout << "🔧 Initializing matrices...\n";

    for (int i = 0; i < MR * K; i++) A[i] = 1.0f;
    for (int i = 0; i < K * NR; i++) B[i] = 0.5f;
    std::memset(C, 0, MR * NR * sizeof(float));
    std::memset(C_ref, 0, MR * NR * sizeof(float));

    std::cout << "  A[i] = 1.0, B[i] = 0.5\n";
    std::cout << "  Expected C[i,j] = 1.0 * 0.5 * " << K << " = " << (1.0f * 0.5f * K) << "\n\n";

    // ========================================
    // STEP 3: Run reference (for validation)
    // ========================================
    std::cout << "✅ Running reference implementation (scalar)...\n";
    reference_matmul_6x16(A, B, C_ref);
    std::cout << "  Reference C[0,0] = " << C_ref[0] << "\n\n";

    // ========================================
    // STEP 4: Benchmark intrinsics baseline
    // ========================================
    std::cout << "🚀 BENCHMARK RESULTS:\n";
    std::cout << "════════════════════════════════════════════════════════\n";

    double gflops_intrinsic = benchmark_kernel(
        intrinsic_microkernel_6x16, A, B, C,
        "AVX2 Intrinsics (Hand-written baseline)", ITERATIONS);

    std::cout << "\n";

    // ========================================
    // STEP 5: Benchmark MLIR-generated kernel (if linked)
    // ========================================
#ifdef HAS_MLIR_KERNEL
    double gflops_mlir = benchmark_kernel(
        micro_kernel_6x16, A, B, C,
        "MLIR-Generated Kernel", ITERATIONS);

    std::cout << "\n════════════════════════════════════════════════════════\n";
    std::cout << "📊 COMPARISON:\n";
    std::cout << "  Intrinsics: " << gflops_intrinsic << " GFLOPS\n";
    std::cout << "  MLIR:       " << gflops_mlir << " GFLOPS\n";
    std::cout << "  Ratio:      " << (gflops_mlir / gflops_intrinsic * 100.0) << "%\n";
#else
    std::cout << "\n════════════════════════════════════════════════════════\n";
    std::cout << "📊 INTRINSICS BASELINE ONLY (MLIR kernel not linked)\n";
    std::cout << "  To enable MLIR kernel comparison:\n";
    std::cout << "  1. Compile micro_kernel.mlir → micro_kernel.o\n";
    std::cout << "  2. Link with -DHAS_MLIR_KERNEL\n";
#endif

    // ========================================
    // STEP 6: Interpretation
    // ========================================
    std::cout << "\n════════════════════════════════════════════════════════\n";
    std::cout << "📈 INTERPRETATION:\n";

    double theoretical_peak = 60.0; // Approximate AVX2 peak at ~4GHz
    double efficiency = (gflops_intrinsic / theoretical_peak) * 100.0;

    if (gflops_intrinsic >= 45.0) {
        std::cout << "  🎉 EXCELLENT! (" << efficiency << "% efficiency)\n";
        std::cout << "     Register allocation is perfect.\n";
        std::cout << "     This is the target for the full matmul.\n";
    } else if (gflops_intrinsic >= 30.0) {
        std::cout << "  ✅ GOOD (" << efficiency << "% efficiency)\n";
        std::cout << "     Close to optimal, minor improvements possible.\n";
    } else if (gflops_intrinsic >= 20.0) {
        std::cout << "  ⚠️  MODERATE (" << efficiency << "% efficiency)\n";
        std::cout << "     Check for register spilling or memory stalls.\n";
    } else {
        std::cout << "  ❌ LOW (" << efficiency << "% efficiency)\n";
        std::cout << "     Something is very wrong:\n";
        std::cout << "     - Register spilling?\n";
        std::cout << "     - Not vectorized?\n";
        std::cout << "     - Memory bandwidth bottleneck?\n";
    }

    // ========================================
    // CLEANUP
    // ========================================
    std::free(A);
    std::free(B);
    std::free(C);
    std::free(C_ref);

    return 0;
}

