#!/usr/bin/env python3
"""
Compiles GLSL compute shaders to SPIR-V and generates a zero-dependency C++ header src/runtime/VulkanShaders.h
"""
import os
import subprocess
import struct

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SHADERS_DIR = os.path.join(ROOT, "shaders")
OUTPUT_HEADER = os.path.join(ROOT, "src", "runtime", "VulkanShaders.h")

def compile_shader(src_path):
    spv_path = src_path + ".spv"
    cmd = ["glslc", "-O", src_path, "-o", spv_path]
    print(f"Compiling {os.path.basename(src_path)} -> {os.path.basename(spv_path)}")
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        print("glslc error:", res.stderr)
        raise RuntimeError(f"Failed to compile {src_path}")
    with open(spv_path, "rb") as f:
        data = f.read()
    if os.path.exists(spv_path):
        os.remove(spv_path)
    return data

def main():
    shaders = {
        "bitlinear_tl1": os.path.join(SHADERS_DIR, "bitlinear_tl1.comp"),
        "gemm_f32": os.path.join(SHADERS_DIR, "gemm_f32.comp"),
        "rmsnorm": os.path.join(SHADERS_DIR, "rmsnorm.comp"),
    }
    
    header_content = """#pragma once
/**
 * VulkanShaders.h — Precompiled SPIR-V Compute Shaders for Tenzo GPU Runtime
 * Auto-generated by scripts/compile_shaders.py
 * Embedded as const uint32_t arrays for zero-dependency execution across Android/Linux/Windows.
 */

#include <vector>
#include <cstdint>

namespace tenzo {
namespace runtime {
namespace shaders {

"""

    for name, path in shaders.items():
        spv_bytes = compile_shader(path)
        words = list(struct.unpack(f"<{len(spv_bytes)//4}I", spv_bytes))
        
        header_content += f"// Shader: {name} ({len(words)} uint32 words, {len(spv_bytes)} bytes)\n"
        header_content += f"inline const uint32_t {name}_spv[{len(words)}] = {{\n    "
        
        for i, w in enumerate(words):
            header_content += f"0x{w:08x}, "
            if (i + 1) % 8 == 0:
                header_content += "\n    "
        header_content += "\n};\n\n"
        
        header_content += f"inline std::vector<uint32_t> get_{name}_spirv() {{\n"
        header_content += f"    return std::vector<uint32_t>({name}_spv, {name}_spv + {len(words)});\n"
        header_content += "}\n\n"

    header_content += """} // namespace shaders
} // namespace runtime
} // namespace tenzo
"""

    with open(OUTPUT_HEADER, "w", encoding="utf-8") as f:
        f.write(header_content)
    print(f"✅ Successfully generated {OUTPUT_HEADER} ({os.path.getsize(OUTPUT_HEADER)} bytes)")

if __name__ == "__main__":
    main()
