// Generated by Tenzo PyTorch FX Frontend (Zero-Copy Bridge)
module {

  func.func @main(%arg0: tensor<1x1xi32>, %arg1: memref<?xi8>, %arg2: tensor<1x4x1024x32xf32>, %arg3: tensor<1x4x1024x32xf32>, %arg4: tensor<1xi32>) -> (tensor<1x1x320xf32>, tensor<1x4x1024x32xf32>, tensor<1x4x1024x32xf32>) attributes {llvm.emit_c_interface} {
    %v0 = arith.constant 0 : index
    %v1 = memref.view %arg1[%v0][] : memref<?xi8> to memref<320x128xf32>
    %v2 = bufferization.to_tensor %v1 : memref<320x128xf32> to tensor<320x128xf32>
    %v3 = "tenzo.embedding"(%arg0, %v2) : (tensor<1x1xi32>, tensor<320x128xf32>) -> tensor<1x1x128xf32>
    %v4 = arith.constant 163840 : index
    %v5 = memref.view %arg1[%v4][] : memref<?xi8> to memref<128xf32>
    %v6 = bufferization.to_tensor %v5 : memref<128xf32> to tensor<128xf32>
    %v7 = "tenzo.rmsnorm"(%v3, %v6) {eps = 1.00000000e-06 : f32} : (tensor<1x1x128xf32>, tensor<128xf32>) -> tensor<1x1x128xf32>
    %v8 = arith.constant 164352 : index
    %v9 = memref.view %arg1[%v8][] : memref<?xi8> to memref<128x32xi8>
    %v10 = bufferization.to_tensor %v9 : memref<128x32xi8> to tensor<128x32xi8>
    %v11 = arith.constant 4.42272462e-02 : f32
    %v12 = "tenzo.dequantize"(%v10, %v11) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<128x32xi8>, f32) -> tensor<128x128xf32>
    %v13 = "tenzo.matmul"(%v7, %v12) : (tensor<1x1x128xf32>, tensor<128x128xf32>) -> tensor<1x1x128xf32>
    %v14 = arith.constant 168448 : index
    %v15 = memref.view %arg1[%v14][] : memref<?xi8> to memref<1x1x128xf32>
    %v16 = bufferization.to_tensor %v15 : memref<1x1x128xf32> to tensor<1x1x128xf32>
    %v17 = "tenzo.add"(%v13, %v16) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v18 = tensor.expand_shape %v17 [[0], [1], [2, 3]] output_shape [1, 1, 4, 32] : tensor<1x1x128xf32> into tensor<1x1x4x32xf32>
    %v19 = tensor.empty() : tensor<1x4x1x32xf32>
    %v20 = linalg.transpose ins(%v18 : tensor<1x1x4x32xf32>) outs(%v19 : tensor<1x4x1x32xf32>) permutation = [0, 2, 1, 3]
    %v21 = arith.constant 168480 : index
    %v22 = memref.view %arg1[%v21][] : memref<?xi8> to memref<128x32xi8>
    %v23 = bufferization.to_tensor %v22 : memref<128x32xi8> to tensor<128x32xi8>
    %v24 = arith.constant 4.41823229e-02 : f32
    %v25 = "tenzo.dequantize"(%v23, %v24) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<128x32xi8>, f32) -> tensor<128x128xf32>
    %v26 = "tenzo.matmul"(%v7, %v25) : (tensor<1x1x128xf32>, tensor<128x128xf32>) -> tensor<1x1x128xf32>
    %v27 = arith.constant 172576 : index
    %v28 = memref.view %arg1[%v27][] : memref<?xi8> to memref<1x1x128xf32>
    %v29 = bufferization.to_tensor %v28 : memref<1x1x128xf32> to tensor<1x1x128xf32>
    %v30 = "tenzo.add"(%v26, %v29) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v31 = tensor.expand_shape %v30 [[0], [1], [2, 3]] output_shape [1, 1, 4, 32] : tensor<1x1x128xf32> into tensor<1x1x4x32xf32>
    %v32 = tensor.empty() : tensor<1x4x1x32xf32>
    %v33 = linalg.transpose ins(%v31 : tensor<1x1x4x32xf32>) outs(%v32 : tensor<1x4x1x32xf32>) permutation = [0, 2, 1, 3]
    %v34 = arith.constant 172608 : index
    %v35 = memref.view %arg1[%v34][] : memref<?xi8> to memref<128x32xi8>
    %v36 = bufferization.to_tensor %v35 : memref<128x32xi8> to tensor<128x32xi8>
    %v37 = arith.constant 4.41496857e-02 : f32
    %v38 = "tenzo.dequantize"(%v36, %v37) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<128x32xi8>, f32) -> tensor<128x128xf32>
    %v39 = "tenzo.matmul"(%v7, %v38) : (tensor<1x1x128xf32>, tensor<128x128xf32>) -> tensor<1x1x128xf32>
    %v40 = arith.constant 176704 : index
    %v41 = memref.view %arg1[%v40][] : memref<?xi8> to memref<1x1x128xf32>
    %v42 = bufferization.to_tensor %v41 : memref<1x1x128xf32> to tensor<1x1x128xf32>
    %v43 = "tenzo.add"(%v39, %v42) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v44 = tensor.expand_shape %v43 [[0], [1], [2, 3]] output_shape [1, 1, 4, 32] : tensor<1x1x128xf32> into tensor<1x1x4x32xf32>
    %v45 = tensor.empty() : tensor<1x4x1x32xf32>
    %v46 = linalg.transpose ins(%v44 : tensor<1x1x4x32xf32>) outs(%v45 : tensor<1x4x1x32xf32>) permutation = [0, 2, 1, 3]
    %v47 = "tenzo.rope"(%v20, %arg4) : (tensor<1x4x1x32xf32>, tensor<1xi32>) -> tensor<1x4x1x32xf32>
    %v48 = "tenzo.rope"(%v33, %arg4) : (tensor<1x4x1x32xf32>, tensor<1xi32>) -> tensor<1x4x1x32xf32>
    %v49, %v50 = "tenzo.kv_cache_update"(%arg2, %arg3, %v48, %v46, %arg4) : (tensor<1x4x1024x32xf32>, tensor<1x4x1024x32xf32>, tensor<1x4x1x32xf32>, tensor<1x4x1x32xf32>, tensor<1xi32>) -> (tensor<1x4x1024x32xf32>, tensor<1x4x1024x32xf32>)
    %v51 = "tenzo.attention"(%v47, %v49, %v50, %arg4) : (tensor<1x4x1x32xf32>, tensor<1x4x1024x32xf32>, tensor<1x4x1024x32xf32>, tensor<1xi32>) -> tensor<1x4x1x32xf32>
    %v52 = tensor.empty() : tensor<1x1x4x32xf32>
    %v53 = linalg.transpose ins(%v51 : tensor<1x4x1x32xf32>) outs(%v52 : tensor<1x1x4x32xf32>) permutation = [0, 2, 1, 3]
    %v54 = tensor.collapse_shape %v53 [[0], [1], [2, 3]] : tensor<1x1x4x32xf32> into tensor<1x1x128xf32>
    %v55 = arith.constant 176736 : index
    %v56 = memref.view %arg1[%v55][] : memref<?xi8> to memref<128x32xi8>
    %v57 = bufferization.to_tensor %v56 : memref<128x32xi8> to tensor<128x32xi8>
    %v58 = arith.constant 4.42162789e-02 : f32
    %v59 = "tenzo.dequantize"(%v57, %v58) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<128x32xi8>, f32) -> tensor<128x128xf32>
    %v60 = "tenzo.matmul"(%v54, %v59) : (tensor<1x1x128xf32>, tensor<128x128xf32>) -> tensor<1x1x128xf32>
    %v61 = arith.constant 180832 : index
    %v62 = memref.view %arg1[%v61][] : memref<?xi8> to memref<1x1x128xf32>
    %v63 = bufferization.to_tensor %v62 : memref<1x1x128xf32> to tensor<1x1x128xf32>
    %v64 = "tenzo.add"(%v60, %v63) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v65 = "tenzo.add"(%v3, %v64) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v66 = arith.constant 180864 : index
    %v67 = memref.view %arg1[%v66][] : memref<?xi8> to memref<128xf32>
    %v68 = bufferization.to_tensor %v67 : memref<128xf32> to tensor<128xf32>
    %v69 = "tenzo.rmsnorm"(%v65, %v68) {eps = 1.00000000e-06 : f32} : (tensor<1x1x128xf32>, tensor<128xf32>) -> tensor<1x1x128xf32>
    %v70 = arith.constant 181376 : index
    %v71 = memref.view %arg1[%v70][] : memref<?xi8> to memref<256x32xi8>
    %v72 = bufferization.to_tensor %v71 : memref<256x32xi8> to tensor<256x32xi8>
    %v73 = arith.constant 4.42814529e-02 : f32
    %v74 = "tenzo.dequantize"(%v72, %v73) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<256x32xi8>, f32) -> tensor<256x128xf32>
    %v75 = "tenzo.matmul"(%v69, %v74) : (tensor<1x1x128xf32>, tensor<256x128xf32>) -> tensor<1x1x256xf32>
    %v76 = arith.constant 189568 : index
    %v77 = memref.view %arg1[%v76][] : memref<?xi8> to memref<1x1x256xf32>
    %v78 = bufferization.to_tensor %v77 : memref<1x1x256xf32> to tensor<1x1x256xf32>
    %v79 = "tenzo.add"(%v75, %v78) : (tensor<1x1x256xf32>, tensor<1x1x256xf32>) -> tensor<1x1x256xf32>
    %v80 = "tenzo.relu"(%v79) : (tensor<1x1x256xf32>) -> tensor<1x1x256xf32>
    %v81 = arith.constant 189632 : index
    %v82 = memref.view %arg1[%v81][] : memref<?xi8> to memref<128x64xi8>
    %v83 = bufferization.to_tensor %v82 : memref<128x64xi8> to tensor<128x64xi8>
    %v84 = arith.constant 3.14373672e-02 : f32
    %v85 = "tenzo.dequantize"(%v83, %v84) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<128x64xi8>, f32) -> tensor<128x256xf32>
    %v86 = "tenzo.matmul"(%v80, %v85) : (tensor<1x1x256xf32>, tensor<128x256xf32>) -> tensor<1x1x128xf32>
    %v87 = arith.constant 197824 : index
    %v88 = memref.view %arg1[%v87][] : memref<?xi8> to memref<1x1x128xf32>
    %v89 = bufferization.to_tensor %v88 : memref<1x1x128xf32> to tensor<1x1x128xf32>
    %v90 = "tenzo.add"(%v86, %v89) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v91 = "tenzo.add"(%v65, %v90) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v92 = arith.constant 197856 : index
    %v93 = memref.view %arg1[%v92][] : memref<?xi8> to memref<128xf32>
    %v94 = bufferization.to_tensor %v93 : memref<128xf32> to tensor<128xf32>
    %v95 = "tenzo.rmsnorm"(%v91, %v94) {eps = 1.00000000e-06 : f32} : (tensor<1x1x128xf32>, tensor<128xf32>) -> tensor<1x1x128xf32>
    %v96 = arith.constant 198368 : index
    %v97 = memref.view %arg1[%v96][] : memref<?xi8> to memref<128x32xi8>
    %v98 = bufferization.to_tensor %v97 : memref<128x32xi8> to tensor<128x32xi8>
    %v99 = arith.constant 4.40559238e-02 : f32
    %v100 = "tenzo.dequantize"(%v98, %v99) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<128x32xi8>, f32) -> tensor<128x128xf32>
    %v101 = "tenzo.matmul"(%v95, %v100) : (tensor<1x1x128xf32>, tensor<128x128xf32>) -> tensor<1x1x128xf32>
    %v102 = arith.constant 202464 : index
    %v103 = memref.view %arg1[%v102][] : memref<?xi8> to memref<1x1x128xf32>
    %v104 = bufferization.to_tensor %v103 : memref<1x1x128xf32> to tensor<1x1x128xf32>
    %v105 = "tenzo.add"(%v101, %v104) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v106 = tensor.expand_shape %v105 [[0], [1], [2, 3]] output_shape [1, 1, 4, 32] : tensor<1x1x128xf32> into tensor<1x1x4x32xf32>
    %v107 = tensor.empty() : tensor<1x4x1x32xf32>
    %v108 = linalg.transpose ins(%v106 : tensor<1x1x4x32xf32>) outs(%v107 : tensor<1x4x1x32xf32>) permutation = [0, 2, 1, 3]
    %v109 = arith.constant 202496 : index
    %v110 = memref.view %arg1[%v109][] : memref<?xi8> to memref<128x32xi8>
    %v111 = bufferization.to_tensor %v110 : memref<128x32xi8> to tensor<128x32xi8>
    %v112 = arith.constant 4.41119000e-02 : f32
    %v113 = "tenzo.dequantize"(%v111, %v112) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<128x32xi8>, f32) -> tensor<128x128xf32>
    %v114 = "tenzo.matmul"(%v95, %v113) : (tensor<1x1x128xf32>, tensor<128x128xf32>) -> tensor<1x1x128xf32>
    %v115 = arith.constant 206592 : index
    %v116 = memref.view %arg1[%v115][] : memref<?xi8> to memref<1x1x128xf32>
    %v117 = bufferization.to_tensor %v116 : memref<1x1x128xf32> to tensor<1x1x128xf32>
    %v118 = "tenzo.add"(%v114, %v117) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v119 = tensor.expand_shape %v118 [[0], [1], [2, 3]] output_shape [1, 1, 4, 32] : tensor<1x1x128xf32> into tensor<1x1x4x32xf32>
    %v120 = tensor.empty() : tensor<1x4x1x32xf32>
    %v121 = linalg.transpose ins(%v119 : tensor<1x1x4x32xf32>) outs(%v120 : tensor<1x4x1x32xf32>) permutation = [0, 2, 1, 3]
    %v122 = arith.constant 206624 : index
    %v123 = memref.view %arg1[%v122][] : memref<?xi8> to memref<128x32xi8>
    %v124 = bufferization.to_tensor %v123 : memref<128x32xi8> to tensor<128x32xi8>
    %v125 = arith.constant 4.43957075e-02 : f32
    %v126 = "tenzo.dequantize"(%v124, %v125) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<128x32xi8>, f32) -> tensor<128x128xf32>
    %v127 = "tenzo.matmul"(%v95, %v126) : (tensor<1x1x128xf32>, tensor<128x128xf32>) -> tensor<1x1x128xf32>
    %v128 = arith.constant 210720 : index
    %v129 = memref.view %arg1[%v128][] : memref<?xi8> to memref<1x1x128xf32>
    %v130 = bufferization.to_tensor %v129 : memref<1x1x128xf32> to tensor<1x1x128xf32>
    %v131 = "tenzo.add"(%v127, %v130) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v132 = tensor.expand_shape %v131 [[0], [1], [2, 3]] output_shape [1, 1, 4, 32] : tensor<1x1x128xf32> into tensor<1x1x4x32xf32>
    %v133 = tensor.empty() : tensor<1x4x1x32xf32>
    %v134 = linalg.transpose ins(%v132 : tensor<1x1x4x32xf32>) outs(%v133 : tensor<1x4x1x32xf32>) permutation = [0, 2, 1, 3]
    %v135 = "tenzo.rope"(%v108, %arg4) : (tensor<1x4x1x32xf32>, tensor<1xi32>) -> tensor<1x4x1x32xf32>
    %v136 = "tenzo.rope"(%v121, %arg4) : (tensor<1x4x1x32xf32>, tensor<1xi32>) -> tensor<1x4x1x32xf32>
    %v137, %v138 = "tenzo.kv_cache_update"(%v49, %v50, %v136, %v134, %arg4) : (tensor<1x4x1024x32xf32>, tensor<1x4x1024x32xf32>, tensor<1x4x1x32xf32>, tensor<1x4x1x32xf32>, tensor<1xi32>) -> (tensor<1x4x1024x32xf32>, tensor<1x4x1024x32xf32>)
    %v139 = "tenzo.attention"(%v135, %v137, %v138, %arg4) : (tensor<1x4x1x32xf32>, tensor<1x4x1024x32xf32>, tensor<1x4x1024x32xf32>, tensor<1xi32>) -> tensor<1x4x1x32xf32>
    %v140 = tensor.empty() : tensor<1x1x4x32xf32>
    %v141 = linalg.transpose ins(%v139 : tensor<1x4x1x32xf32>) outs(%v140 : tensor<1x1x4x32xf32>) permutation = [0, 2, 1, 3]
    %v142 = tensor.collapse_shape %v141 [[0], [1], [2, 3]] : tensor<1x1x4x32xf32> into tensor<1x1x128xf32>
    %v143 = arith.constant 210752 : index
    %v144 = memref.view %arg1[%v143][] : memref<?xi8> to memref<128x32xi8>
    %v145 = bufferization.to_tensor %v144 : memref<128x32xi8> to tensor<128x32xi8>
    %v146 = arith.constant 4.42331284e-02 : f32
    %v147 = "tenzo.dequantize"(%v145, %v146) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<128x32xi8>, f32) -> tensor<128x128xf32>
    %v148 = "tenzo.matmul"(%v142, %v147) : (tensor<1x1x128xf32>, tensor<128x128xf32>) -> tensor<1x1x128xf32>
    %v149 = arith.constant 214848 : index
    %v150 = memref.view %arg1[%v149][] : memref<?xi8> to memref<1x1x128xf32>
    %v151 = bufferization.to_tensor %v150 : memref<1x1x128xf32> to tensor<1x1x128xf32>
    %v152 = "tenzo.add"(%v148, %v151) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v153 = "tenzo.add"(%v91, %v152) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v154 = arith.constant 214880 : index
    %v155 = memref.view %arg1[%v154][] : memref<?xi8> to memref<128xf32>
    %v156 = bufferization.to_tensor %v155 : memref<128xf32> to tensor<128xf32>
    %v157 = "tenzo.rmsnorm"(%v153, %v156) {eps = 1.00000000e-06 : f32} : (tensor<1x1x128xf32>, tensor<128xf32>) -> tensor<1x1x128xf32>
    %v158 = arith.constant 215392 : index
    %v159 = memref.view %arg1[%v158][] : memref<?xi8> to memref<256x32xi8>
    %v160 = bufferization.to_tensor %v159 : memref<256x32xi8> to tensor<256x32xi8>
    %v161 = arith.constant 4.43648621e-02 : f32
    %v162 = "tenzo.dequantize"(%v160, %v161) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<256x32xi8>, f32) -> tensor<256x128xf32>
    %v163 = "tenzo.matmul"(%v157, %v162) : (tensor<1x1x128xf32>, tensor<256x128xf32>) -> tensor<1x1x256xf32>
    %v164 = arith.constant 223584 : index
    %v165 = memref.view %arg1[%v164][] : memref<?xi8> to memref<1x1x256xf32>
    %v166 = bufferization.to_tensor %v165 : memref<1x1x256xf32> to tensor<1x1x256xf32>
    %v167 = "tenzo.add"(%v163, %v166) : (tensor<1x1x256xf32>, tensor<1x1x256xf32>) -> tensor<1x1x256xf32>
    %v168 = "tenzo.relu"(%v167) : (tensor<1x1x256xf32>) -> tensor<1x1x256xf32>
    %v169 = arith.constant 223648 : index
    %v170 = memref.view %arg1[%v169][] : memref<?xi8> to memref<128x64xi8>
    %v171 = bufferization.to_tensor %v170 : memref<128x64xi8> to tensor<128x64xi8>
    %v172 = arith.constant 3.10880579e-02 : f32
    %v173 = "tenzo.dequantize"(%v171, %v172) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<128x64xi8>, f32) -> tensor<128x256xf32>
    %v174 = "tenzo.matmul"(%v168, %v173) : (tensor<1x1x256xf32>, tensor<128x256xf32>) -> tensor<1x1x128xf32>
    %v175 = arith.constant 231840 : index
    %v176 = memref.view %arg1[%v175][] : memref<?xi8> to memref<1x1x128xf32>
    %v177 = bufferization.to_tensor %v176 : memref<1x1x128xf32> to tensor<1x1x128xf32>
    %v178 = "tenzo.add"(%v174, %v177) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v179 = "tenzo.add"(%v153, %v178) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v180 = arith.constant 231872 : index
    %v181 = memref.view %arg1[%v180][] : memref<?xi8> to memref<128xf32>
    %v182 = bufferization.to_tensor %v181 : memref<128xf32> to tensor<128xf32>
    %v183 = "tenzo.rmsnorm"(%v179, %v182) {eps = 1.00000000e-06 : f32} : (tensor<1x1x128xf32>, tensor<128xf32>) -> tensor<1x1x128xf32>
    %v184 = arith.constant 232384 : index
    %v185 = memref.view %arg1[%v184][] : memref<?xi8> to memref<320x32xi8>
    %v186 = bufferization.to_tensor %v185 : memref<320x32xi8> to tensor<320x32xi8>
    %v187 = arith.constant 4.43131402e-02 : f32
    %v188 = "tenzo.dequantize"(%v186, %v187) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<320x32xi8>, f32) -> tensor<320x128xf32>
    %v189 = "tenzo.matmul"(%v183, %v188) : (tensor<1x1x128xf32>, tensor<320x128xf32>) -> tensor<1x1x320xf32>
    %v190 = arith.constant 242624 : index
    %v191 = memref.view %arg1[%v190][] : memref<?xi8> to memref<1x1x320xf32>
    %v192 = bufferization.to_tensor %v191 : memref<1x1x320xf32> to tensor<1x1x320xf32>
    %v193 = "tenzo.add"(%v189, %v192) : (tensor<1x1x320xf32>, tensor<1x1x320xf32>) -> tensor<1x1x320xf32>
    return %v193, %v137, %v138 : tensor<1x1x320xf32>, tensor<1x4x1024x32xf32>, tensor<1x4x1024x32xf32>
  }
}