// Generated by Tenzo PyTorch FX Frontend (Zero-Copy Bridge)
module {

  func.func @main(%arg0: tensor<1x1x128xf32>, %arg1: memref<?xi8>, %arg2: tensor<1x4x1024x32xf32>, %arg3: tensor<1x4x1024x32xf32>, %arg4: tensor<1xi32>) -> (tensor<1x1x128xf32>, tensor<1x4x1024x32xf32>, tensor<1x4x1024x32xf32>) attributes {llvm.emit_c_interface} {
    %v0 = arith.constant 0 : index
    %v1 = memref.view %arg1[%v0][] : memref<?xi8> to memref<128x32xi8>
    %v2 = bufferization.to_tensor %v1 : memref<128x32xi8> to tensor<128x32xi8>
    %v3 = arith.constant 4.45707962e-02 : f32
    %v4 = "tenzo.dequantize"(%v2, %v3) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<128x32xi8>, f32) -> tensor<128x128xf32>
    %v5 = "tenzo.matmul"(%arg0, %v4) : (tensor<1x1x128xf32>, tensor<128x128xf32>) -> tensor<1x1x128xf32>
    %v6 = arith.constant 4096 : index
    %v7 = memref.view %arg1[%v6][] : memref<?xi8> to memref<1x1x128xf32>
    %v8 = bufferization.to_tensor %v7 : memref<1x1x128xf32> to tensor<1x1x128xf32>
    %v9 = "tenzo.add"(%v5, %v8) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v10 = tensor.expand_shape %v9 [[0], [1], [2, 3]] output_shape [1, 1, 4, 32] : tensor<1x1x128xf32> into tensor<1x1x4x32xf32>
    %v11 = tensor.empty() : tensor<1x4x1x32xf32>
    %v12 = linalg.transpose ins(%v10 : tensor<1x1x4x32xf32>) outs(%v11 : tensor<1x4x1x32xf32>) permutation = [0, 2, 1, 3]
    %v13 = arith.constant 4128 : index
    %v14 = memref.view %arg1[%v13][] : memref<?xi8> to memref<128x32xi8>
    %v15 = bufferization.to_tensor %v14 : memref<128x32xi8> to tensor<128x32xi8>
    %v16 = arith.constant 4.41555046e-02 : f32
    %v17 = "tenzo.dequantize"(%v15, %v16) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<128x32xi8>, f32) -> tensor<128x128xf32>
    %v18 = "tenzo.matmul"(%arg0, %v17) : (tensor<1x1x128xf32>, tensor<128x128xf32>) -> tensor<1x1x128xf32>
    %v19 = arith.constant 8224 : index
    %v20 = memref.view %arg1[%v19][] : memref<?xi8> to memref<1x1x128xf32>
    %v21 = bufferization.to_tensor %v20 : memref<1x1x128xf32> to tensor<1x1x128xf32>
    %v22 = "tenzo.add"(%v18, %v21) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v23 = tensor.expand_shape %v22 [[0], [1], [2, 3]] output_shape [1, 1, 4, 32] : tensor<1x1x128xf32> into tensor<1x1x4x32xf32>
    %v24 = tensor.empty() : tensor<1x4x1x32xf32>
    %v25 = linalg.transpose ins(%v23 : tensor<1x1x4x32xf32>) outs(%v24 : tensor<1x4x1x32xf32>) permutation = [0, 2, 1, 3]
    %v26 = arith.constant 8256 : index
    %v27 = memref.view %arg1[%v26][] : memref<?xi8> to memref<128x32xi8>
    %v28 = bufferization.to_tensor %v27 : memref<128x32xi8> to tensor<128x32xi8>
    %v29 = arith.constant 4.43285666e-02 : f32
    %v30 = "tenzo.dequantize"(%v28, %v29) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<128x32xi8>, f32) -> tensor<128x128xf32>
    %v31 = "tenzo.matmul"(%arg0, %v30) : (tensor<1x1x128xf32>, tensor<128x128xf32>) -> tensor<1x1x128xf32>
    %v32 = arith.constant 12352 : index
    %v33 = memref.view %arg1[%v32][] : memref<?xi8> to memref<1x1x128xf32>
    %v34 = bufferization.to_tensor %v33 : memref<1x1x128xf32> to tensor<1x1x128xf32>
    %v35 = "tenzo.add"(%v31, %v34) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v36 = tensor.expand_shape %v35 [[0], [1], [2, 3]] output_shape [1, 1, 4, 32] : tensor<1x1x128xf32> into tensor<1x1x4x32xf32>
    %v37 = tensor.empty() : tensor<1x4x1x32xf32>
    %v38 = linalg.transpose ins(%v36 : tensor<1x1x4x32xf32>) outs(%v37 : tensor<1x4x1x32xf32>) permutation = [0, 2, 1, 3]
    %v39 = "tenzo.rope"(%v12, %arg4) : (tensor<1x4x1x32xf32>, tensor<1xi32>) -> tensor<1x4x1x32xf32>
    %v40 = "tenzo.rope"(%v25, %arg4) : (tensor<1x4x1x32xf32>, tensor<1xi32>) -> tensor<1x4x1x32xf32>
    %v41, %v42 = "tenzo.kv_cache_update"(%arg2, %arg3, %v40, %v38, %arg4) : (tensor<1x4x1024x32xf32>, tensor<1x4x1024x32xf32>, tensor<1x4x1x32xf32>, tensor<1x4x1x32xf32>, tensor<1xi32>) -> (tensor<1x4x1024x32xf32>, tensor<1x4x1024x32xf32>)
    %v43 = "tenzo.attention"(%v39, %v41, %v42, %arg4) : (tensor<1x4x1x32xf32>, tensor<1x4x1024x32xf32>, tensor<1x4x1024x32xf32>, tensor<1xi32>) -> tensor<1x4x1x32xf32>
    %v44 = tensor.empty() : tensor<1x1x4x32xf32>
    %v45 = linalg.transpose ins(%v43 : tensor<1x4x1x32xf32>) outs(%v44 : tensor<1x1x4x32xf32>) permutation = [0, 2, 1, 3]
    %v46 = tensor.collapse_shape %v45 [[0], [1], [2, 3]] : tensor<1x1x4x32xf32> into tensor<1x1x128xf32>
    %v47 = arith.constant 12384 : index
    %v48 = memref.view %arg1[%v47][] : memref<?xi8> to memref<128x32xi8>
    %v49 = bufferization.to_tensor %v48 : memref<128x32xi8> to tensor<128x32xi8>
    %v50 = arith.constant 4.40602750e-02 : f32
    %v51 = "tenzo.dequantize"(%v49, %v50) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<128x32xi8>, f32) -> tensor<128x128xf32>
    %v52 = "tenzo.matmul"(%v46, %v51) : (tensor<1x1x128xf32>, tensor<128x128xf32>) -> tensor<1x1x128xf32>
    %v53 = arith.constant 16480 : index
    %v54 = memref.view %arg1[%v53][] : memref<?xi8> to memref<1x1x128xf32>
    %v55 = bufferization.to_tensor %v54 : memref<1x1x128xf32> to tensor<1x1x128xf32>
    %v56 = "tenzo.add"(%v52, %v55) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v57 = "tenzo.add"(%arg0, %v56) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v58 = arith.constant 16512 : index
    %v59 = memref.view %arg1[%v58][] : memref<?xi8> to memref<256x32xi8>
    %v60 = bufferization.to_tensor %v59 : memref<256x32xi8> to tensor<256x32xi8>
    %v61 = arith.constant 4.41878811e-02 : f32
    %v62 = "tenzo.dequantize"(%v60, %v61) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<256x32xi8>, f32) -> tensor<256x128xf32>
    %v63 = "tenzo.matmul"(%v57, %v62) : (tensor<1x1x128xf32>, tensor<256x128xf32>) -> tensor<1x1x256xf32>
    %v64 = arith.constant 24704 : index
    %v65 = memref.view %arg1[%v64][] : memref<?xi8> to memref<1x1x256xf32>
    %v66 = bufferization.to_tensor %v65 : memref<1x1x256xf32> to tensor<1x1x256xf32>
    %v67 = "tenzo.add"(%v63, %v66) : (tensor<1x1x256xf32>, tensor<1x1x256xf32>) -> tensor<1x1x256xf32>
    %v68 = "tenzo.relu"(%v67) : (tensor<1x1x256xf32>) -> tensor<1x1x256xf32>
    %v69 = arith.constant 24768 : index
    %v70 = memref.view %arg1[%v69][] : memref<?xi8> to memref<128x64xi8>
    %v71 = bufferization.to_tensor %v70 : memref<128x64xi8> to tensor<128x64xi8>
    %v72 = arith.constant 3.13445479e-02 : f32
    %v73 = "tenzo.dequantize"(%v71, %v72) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<128x64xi8>, f32) -> tensor<128x256xf32>
    %v74 = "tenzo.matmul"(%v68, %v73) : (tensor<1x1x256xf32>, tensor<128x256xf32>) -> tensor<1x1x128xf32>
    %v75 = arith.constant 32960 : index
    %v76 = memref.view %arg1[%v75][] : memref<?xi8> to memref<1x1x128xf32>
    %v77 = bufferization.to_tensor %v76 : memref<1x1x128xf32> to tensor<1x1x128xf32>
    %v78 = "tenzo.add"(%v74, %v77) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    %v79 = "tenzo.add"(%v57, %v78) : (tensor<1x1x128xf32>, tensor<1x1x128xf32>) -> tensor<1x1x128xf32>
    return %v79, %v41, %v42 : tensor<1x1x128xf32>, tensor<1x4x1024x32xf32>, tensor<1x4x1024x32xf32>
  }
}