import os
import sys
import argparse
import struct
import torch
import numpy as np
from huggingface_hub import hf_hub_download
from safetensors import safe_open
from transformers import AutoTokenizer

def export_bitnet_model(model_name="microsoft/bitnet-b1.58-2B-4T", output_dir="export_output_bitnet", num_layers=2):
    os.makedirs(output_dir, exist_ok=True)
    print(f"[Export BitNet] Exporting model '{model_name}' ({num_layers} layers)...")

    # 1. Download & Extract Tokenizer Vocabulary
    print("[Export BitNet] Extracting Tokenizer Vocabulary...")
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    vocab_dict = tokenizer.get_vocab()
    # Sort by token ID
    sorted_vocab = sorted(vocab_dict.items(), key=lambda x: x[1])

    vocab_path = os.path.join(output_dir, "tokenizer.vocab")
    with open(vocab_path, "w", encoding="utf-8") as f:
        for token_str, token_id in sorted_vocab:
            # Replace newlines/spaces for clean single-line reading
            cleaned_str = token_str.replace("\n", "\\n").replace("\r", "\\r")
            f.write(f"{token_id} {cleaned_str}\n")
    print(f"  ✅ Saved vocabulary ({len(sorted_vocab)} tokens) to {vocab_path}")

    # 2. Download Safetensors
    print("[Export BitNet] Loading Safetensors weights...")
    safetensors_path = hf_hub_download(model_name, "model.safetensors")
    st = safe_open(safetensors_path, framework="pt")

    weights_bin_path = os.path.join(output_dir, "weights.bin")
    weights_file = open(weights_bin_path, "wb")
    current_offset = 0
    weight_metadata = {}

    def write_tensor(name, tensor_data, scale_val=1.0):
        nonlocal current_offset
        # Ensure contiguous bytes
        if tensor_data.dtype == torch.uint8:
            raw_bytes = tensor_data.numpy().tobytes()
            shape = list(tensor_data.shape)
            # Reconstruct original unquantized shape [out_features, in_features]
            orig_shape = [shape[0] * 4, shape[1]]
        elif tensor_data.dtype in (torch.float32, torch.float16, torch.bfloat16):
            raw_bytes = tensor_data.to(torch.float32).numpy().tobytes()
            orig_shape = list(tensor_data.shape)
        else:
            raw_bytes = tensor_data.numpy().tobytes()
            orig_shape = list(tensor_data.shape)

        size_bytes = len(raw_bytes)
        weights_file.write(raw_bytes)
        weight_metadata[name] = {
            "offset": current_offset,
            "size_bytes": size_bytes,
            "shape": orig_shape,
            "scale": scale_val
        }
        current_offset += size_bytes
        return weight_metadata[name]

    # Write Embeddings
    print("  -> Exporting Token Embeddings...")
    embed_w = st.get_tensor("model.embed_tokens.weight")
    write_tensor("model.embed_tokens.weight", embed_w)

    hidden_size = 2560
    ff_dim = 6912
    vocab_size = len(sorted_vocab)

    mlir_lines = [
        "// Generated by Tenzo BitNet 2B Exporter",
        "module {",
        f"  func.func @main(%arg0: tensor<1x1xi32>, %arg1: memref<?xi8>, %arg2: tensor<1x5x1024x128xf32>, %arg3: tensor<1x5x1024x128xf32>, %arg4: tensor<1xi32>) -> (tensor<1x1x{vocab_size}xf32>, tensor<1x5x1024x128xf32>, tensor<1x5x1024x128xf32>) attributes {{llvm.emit_c_interface}} {{"
    ]

    var_counter = 0
    def get_var(t="tensor<*xf32>"):
        nonlocal var_counter
        v = f"%v{var_counter}"
        var_counter += 1
        return v

    # 1. Embedding op
    emb_meta = weight_metadata["model.embed_tokens.weight"]
    c_off = get_var("index")
    mlir_lines.append(f'    {c_off} = arith.constant {emb_meta["offset"]} : index')
    w_mem = get_var(f"memref<{vocab_size}x{hidden_size}xf32>")
    mlir_lines.append(f'    {w_mem} = memref.view %arg1[{c_off}][] : memref<?xi8> to memref<{vocab_size}x{hidden_size}xf32>')
    w_tens = get_var(f"tensor<{vocab_size}x{hidden_size}xf32>")
    mlir_lines.append(f'    {w_tens} = bufferization.to_tensor {w_mem} restrict : memref<{vocab_size}x{hidden_size}xf32> to tensor<{vocab_size}x{hidden_size}xf32>')
    
    cur_x = get_var(f"tensor<1x1x{hidden_size}xf32>")
    mlir_lines.append(f'    {cur_x} = "tenzo.embedding"(%arg0, {w_tens}) : (tensor<1x1xi32>, tensor<{vocab_size}x{hidden_size}xf32>) -> tensor<1x1x{hidden_size}xf32>')

    curr_k = "%arg2"
    curr_v = "%arg3"

    # Export Transformer Layers
    for layer_idx in range(num_layers):
        print(f"  -> Exporting Layer {layer_idx}/{num_layers}...")
        prefix = f"model.layers.{layer_idx}"

        # 1. Input RMSNorm
        in_norm_w = st.get_tensor(f"{prefix}.input_layernorm.weight")
        norm_meta = write_tensor(f"{prefix}.input_layernorm.weight", in_norm_w)
        
        c_off = get_var("index")
        mlir_lines.append(f'    {c_off} = arith.constant {norm_meta["offset"]} : index')
        w_mem = get_var(f"memref<{hidden_size}xf32>")
        mlir_lines.append(f'    {w_mem} = memref.view %arg1[{c_off}][] : memref<?xi8> to memref<{hidden_size}xf32>')
        w_norm_tens = get_var(f"tensor<{hidden_size}xf32>")
        mlir_lines.append(f'    {w_norm_tens} = bufferization.to_tensor {w_mem} restrict : memref<{hidden_size}xf32> to tensor<{hidden_size}xf32>')

        norm_x = get_var(f"tensor<1x1x{hidden_size}xf32>")
        mlir_lines.append(f'    {norm_x} = "tenzo.rmsnorm"({cur_x}, {w_norm_tens}) {{eps = 1.00000000e-05 : f32}} : (tensor<1x1x{hidden_size}xf32>, tensor<{hidden_size}xf32>) -> tensor<1x1x{hidden_size}xf32>')

        # 2. Self Attention Linear projections (q_proj, k_proj, v_proj, o_proj)
        def export_bitlinear(weight_key, input_var, out_features, in_features):
            w = st.get_tensor(weight_key)
            s_tensor = st.get_tensor(f"{weight_key}_scale")
            scale_val = float(s_tensor.to(torch.float32).item()) if s_tensor.numel() == 1 else 1.0
            meta = write_tensor(weight_key, w, scale_val)

            packed_h = out_features // 4
            c_off = get_var("index")
            mlir_lines.append(f'    {c_off} = arith.constant {meta["offset"]} : index')
            
            w_mem = get_var(f"memref<{packed_h}x{in_features}xi8>")
            mlir_lines.append(f'    {w_mem} = memref.view %arg1[{c_off}][] : memref<?xi8> to memref<{packed_h}x{in_features}xi8>')
            w_tens = get_var(f"tensor<{packed_h}x{in_features}xi8>")
            mlir_lines.append(f'    {w_tens} = bufferization.to_tensor {w_mem} restrict : memref<{packed_h}x{in_features}xi8> to tensor<{packed_h}x{in_features}xi8>')

            sc_var = get_var("f32")
            mlir_lines.append(f'    {sc_var} = arith.constant {scale_val:.8e} : f32')

            fp32_w = get_var(f"tensor<{out_features}x{in_features}xf32>")
            mlir_lines.append(
                f'    {fp32_w} = "tenzo.dequantize"({w_tens}, {sc_var}) {{bit_width = 2 : i32, quant_scheme = "ternary"}} : '
                f'(tensor<{packed_h}x{in_features}xi8>, f32) -> tensor<{out_features}x{in_features}xf32>'
            )

            out_v = get_var(f"tensor<1x1x{out_features}xf32>")
            mlir_lines.append(f'    {out_v} = "tenzo.matmul"({input_var}, {fp32_w}) : (tensor<1x1x{in_features}xf32>, tensor<{out_features}x{in_features}xf32>) -> tensor<1x1x{out_features}xf32>')
            return out_v

        q_out = export_bitlinear(f"{prefix}.self_attn.q_proj.weight", norm_x, 2560, 2560)
        k_out = export_bitlinear(f"{prefix}.self_attn.k_proj.weight", norm_x, 640, 2560)
        v_out = export_bitlinear(f"{prefix}.self_attn.v_proj.weight", norm_x, 640, 2560)

        # 4D Reshape for Multi-Head Attention (Q: 20 heads x 128, K/V: 5 heads x 128)
        q_exp = get_var("tensor<1x1x20x128xf32>")
        mlir_lines.append(f'    {q_exp} = tensor.expand_shape {q_out} [[0], [1], [2, 3]] output_shape [1, 1, 20, 128] : tensor<1x1x2560xf32> into tensor<1x1x20x128xf32>')
        empty_q = get_var("tensor<1x20x1x128xf32>")
        mlir_lines.append(f'    {empty_q} = tensor.empty() : tensor<1x20x1x128xf32>')
        q_4d = get_var("tensor<1x20x1x128xf32>")
        mlir_lines.append(f'    {q_4d} = linalg.transpose ins({q_exp} : tensor<1x1x20x128xf32>) outs({empty_q} : tensor<1x20x1x128xf32>) permutation = [0, 2, 1, 3]')

        k_exp = get_var("tensor<1x1x5x128xf32>")
        mlir_lines.append(f'    {k_exp} = tensor.expand_shape {k_out} [[0], [1], [2, 3]] output_shape [1, 1, 5, 128] : tensor<1x1x640xf32> into tensor<1x1x5x128xf32>')
        empty_k = get_var("tensor<1x5x1x128xf32>")
        mlir_lines.append(f'    {empty_k} = tensor.empty() : tensor<1x5x1x128xf32>')
        k_4d = get_var("tensor<1x5x1x128xf32>")
        mlir_lines.append(f'    {k_4d} = linalg.transpose ins({k_exp} : tensor<1x1x5x128xf32>) outs({empty_k} : tensor<1x5x1x128xf32>) permutation = [0, 2, 1, 3]')

        v_exp = get_var("tensor<1x1x5x128xf32>")
        mlir_lines.append(f'    {v_exp} = tensor.expand_shape {v_out} [[0], [1], [2, 3]] output_shape [1, 1, 5, 128] : tensor<1x1x640xf32> into tensor<1x1x5x128xf32>')
        empty_v = get_var("tensor<1x5x1x128xf32>")
        mlir_lines.append(f'    {empty_v} = tensor.empty() : tensor<1x5x1x128xf32>')
        v_4d = get_var("tensor<1x5x1x128xf32>")
        mlir_lines.append(f'    {v_4d} = linalg.transpose ins({v_exp} : tensor<1x1x5x128xf32>) outs({empty_v} : tensor<1x5x1x128xf32>) permutation = [0, 2, 1, 3]')

        # Apply RoPE in 4D
        rope_q = get_var("tensor<1x20x1x128xf32>")
        mlir_lines.append(f'    {rope_q} = "tenzo.rope"({q_4d}, %arg4) : (tensor<1x20x1x128xf32>, tensor<1xi32>) -> tensor<1x20x1x128xf32>')
        rope_k = get_var("tensor<1x5x1x128xf32>")
        mlir_lines.append(f'    {rope_k} = "tenzo.rope"({k_4d}, %arg4) : (tensor<1x5x1x128xf32>, tensor<1xi32>) -> tensor<1x5x1x128xf32>')

        # KV Cache Update
        up_k = get_var("tensor<1x5x1024x128xf32>")
        up_v = get_var("tensor<1x5x1024x128xf32>")
        mlir_lines.append(
            f'    {up_k}, {up_v} = "tenzo.kv_cache_update"({curr_k}, {curr_v}, {rope_k}, {v_4d}, %arg4) : '
            f'(tensor<1x5x1024x128xf32>, tensor<1x5x1024x128xf32>, tensor<1x5x1x128xf32>, tensor<1x5x1x128xf32>, tensor<1xi32>) -> (tensor<1x5x1024x128xf32>, tensor<1x5x1024x128xf32>)'
        )
        curr_k = up_k
        curr_v = up_v

        # Attention
        attn_4d = get_var("tensor<1x20x1x128xf32>")
        mlir_lines.append(
            f'    {attn_4d} = "tenzo.attention"({rope_q}, {curr_k}, {curr_v}, %arg4) : '
            f'(tensor<1x20x1x128xf32>, tensor<1x5x1024x128xf32>, tensor<1x5x1024x128xf32>, tensor<1xi32>) -> tensor<1x20x1x128xf32>'
        )

        empty_attn = get_var("tensor<1x1x20x128xf32>")
        mlir_lines.append(f'    {empty_attn} = tensor.empty() : tensor<1x1x20x128xf32>')
        attn_trans = get_var("tensor<1x1x20x128xf32>")
        mlir_lines.append(f'    {attn_trans} = linalg.transpose ins({attn_4d} : tensor<1x20x1x128xf32>) outs({empty_attn} : tensor<1x1x20x128xf32>) permutation = [0, 2, 1, 3]')

        attn_3d = get_var("tensor<1x1x2560xf32>")
        mlir_lines.append(f'    {attn_3d} = tensor.collapse_shape {attn_trans} [[0], [1], [2, 3]] : tensor<1x1x20x128xf32> into tensor<1x1x2560xf32>')

        o_out = export_bitlinear(f"{prefix}.self_attn.o_proj.weight", attn_3d, 2560, 2560)
        h1 = get_var("tensor<1x1x2560xf32>")
        mlir_lines.append(f'    {h1} = "tenzo.add"({cur_x}, {o_out}) : (tensor<1x1x2560xf32>, tensor<1x1x2560xf32>) -> tensor<1x1x2560xf32>')

        # 3. Post Attention RMSNorm
        post_norm_w = st.get_tensor(f"{prefix}.post_attention_layernorm.weight")
        p_norm_meta = write_tensor(f"{prefix}.post_attention_layernorm.weight", post_norm_w)
        c_off = get_var("index")
        mlir_lines.append(f'    {c_off} = arith.constant {p_norm_meta["offset"]} : index')
        w_mem = get_var(f"memref<{hidden_size}xf32>")
        mlir_lines.append(f'    {w_mem} = memref.view %arg1[{c_off}][] : memref<?xi8> to memref<{hidden_size}xf32>')
        w_pnorm_tens = get_var(f"tensor<{hidden_size}xf32>")
        mlir_lines.append(f'    {w_pnorm_tens} = bufferization.to_tensor {w_mem} restrict : memref<{hidden_size}xf32> to tensor<{hidden_size}xf32>')

        post_norm_h = get_var(f"tensor<1x1x{hidden_size}xf32>")
        mlir_lines.append(f'    {post_norm_h} = "tenzo.rmsnorm"({h1}, {w_pnorm_tens}) {{eps = 1.00000000e-05 : f32}} : (tensor<1x1x{hidden_size}xf32>, tensor<{hidden_size}xf32>) -> tensor<1x1x{hidden_size}xf32>')

        # 4. FFN (gate_proj, up_proj, relu, down_proj)
        gate_out = export_bitlinear(f"{prefix}.mlp.gate_proj.weight", post_norm_h, ff_dim, hidden_size)
        relu_out = get_var(f"tensor<1x1x{ff_dim}xf32>")
        mlir_lines.append(f'    {relu_out} = "tenzo.relu"({gate_out}) : (tensor<1x1x{ff_dim}xf32>) -> tensor<1x1x{ff_dim}xf32>')

        down_out = export_bitlinear(f"{prefix}.mlp.down_proj.weight", relu_out, hidden_size, ff_dim)
        cur_x = get_var(f"tensor<1x1x{hidden_size}xf32>")
        mlir_lines.append(f'    {cur_x} = "tenzo.add"({h1}, {down_out}) : (tensor<1x1x{hidden_size}xf32>, tensor<1x1x{hidden_size}xf32>) -> tensor<1x1x{hidden_size}xf32>')

    # Final LM Head (tied with embed_tokens)
    lm_head_out = get_var(f"tensor<1x1x{vocab_size}xf32>")
    mlir_lines.append(f'    {lm_head_out} = "tenzo.matmul"({cur_x}, {w_tens}) : (tensor<1x1x{hidden_size}xf32>, tensor<{vocab_size}x{hidden_size}xf32>) -> tensor<1x1x{vocab_size}xf32>')
    mlir_lines.append(f'    return {lm_head_out}, {curr_k}, {curr_v} : tensor<1x1x{vocab_size}xf32>, tensor<1x5x1024x128xf32>, tensor<1x5x1024x128xf32>')
    mlir_lines.append("  }")
    mlir_lines.append("}")

    weights_file.close()

    mlir_path = os.path.join(output_dir, "model.mlir")
    with open(mlir_path, "w") as f:
        f.write("\n".join(mlir_lines))

    print(f"\n🎉 Successfully exported BitNet 2B model to '{output_dir}'")
    print(f"  - Model MLIR: {mlir_path}")
    print(f"  - Binary Weights: {weights_bin_path} ({current_offset} bytes)")
    print(f"  - Vocabulary: {vocab_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Export Microsoft BitNet 2B model to Tenzo MLIR format")
    parser.add_argument("--model-name", type=str, default="microsoft/bitnet-b1.58-2B-4T", help="Hugging Face model ID")
    parser.add_argument("--output-dir", type=str, default="export_output_bitnet", help="Directory to save exported files")
    parser.add_argument("--num-layers", type=int, default=2, help="Number of Transformer layers to export (default: 2)")
    args = parser.parse_args()

    export_bitnet_model(model_name=args.model_name, output_dir=args.output_dir, num_layers=args.num_layers)
