import os
import sys

try:
    import numpy as np
    HAS_NUMPY = True
except ImportError:
    HAS_NUMPY = False

# Ensure PyTorch is optionally importable or handled safely
try:
    import torch
    import torch.nn as nn
    import torch.fx as fx
    import torch.nn.functional as F
    HAS_TORCH = True
except ImportError:
    HAS_TORCH = False

sys.path.append(os.path.dirname(os.path.abspath(__file__)))
try:
    from qat import BitLinear, TernaryQuantizeSTE
except ImportError:
    BitLinear = None
    TernaryQuantizeSTE = None


def pack_ternary_list(flat_list) -> bytes:
    """
    Packs a python list of ternary values {-1, 0, 1} into 2-bit representation.
    4 values per byte (uint8).
    
    Encoding:
      0  -> 0b00 (0)
      1  -> 0b01 (1)
     -1  -> 0b10 (2)
    """
    # Pad to multiple of 4
    remainder = len(flat_list) % 4
    if remainder != 0:
        flat_list = flat_list + [0] * (4 - remainder)

    packed_bytes = bytearray()
    for i in range(0, len(flat_list), 4):
        vals = flat_list[i:i+4]
        b = 0
        for shift_idx, v in enumerate(vals):
            enc = 0
            if v == 1:
                enc = 1
            elif v == -1:
                enc = 2
            b |= (enc & 0x03) << (shift_idx * 2)
        packed_bytes.append(b)
        
    return bytes(packed_bytes)


class FXToMLIREmitter:
    def __init__(self, model: "torch.nn.Module", output_dir: str = "."):
        if not HAS_TORCH:
            raise RuntimeError("PyTorch is required for FXToMLIREmitter")

        self.model = model
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

        self.weights_bin_path = os.path.join(self.output_dir, "weights.bin")
        self.weights_file = open(self.weights_bin_path, "wb")
        self.current_byte_offset = 0

        self.weight_metadata = {}  # name -> {offset, size_bytes, shape, orig_dtype}
        self.mlir_lines = []
        self.ssa_map = {}
        self.type_map = {}
        self.var_counter = 0

    def _get_new_var(self, mlir_type: str = "tensor<*xf32>") -> str:
        var_name = f"%v{self.var_counter}"
        self.var_counter += 1
        self.type_map[var_name] = mlir_type
        return var_name

    def _save_weight(self, name: str, tensor: "torch.Tensor", is_ternary: bool = False):
        arr = tensor.detach().cpu().numpy()
        shape = list(arr.shape)
        
        if is_ternary:
            # Scale factor extraction if needed
            scale = float(np.mean(np.abs(arr))) if np.abs(arr).mean() > 0 else 1.0
            arr_quant = np.round(arr / (scale if scale > 0 else 1.0)).clip(-1, 1).astype(np.int8)
            packed_data = pack_ternary_array(arr_quant)
            bit_width = 2
            quant_scheme = "ternary"
        else:
            arr_f32 = arr.astype(np.float32)
            packed_data = arr_f32.tobytes()
            scale = 1.0
            bit_width = 32
            quant_scheme = "none"

        offset = self.current_byte_offset
        size_bytes = len(packed_data)
        self.weights_file.write(packed_data)
        self.current_byte_offset += size_bytes

        meta = {
            "name": name,
            "offset": offset,
            "size_bytes": size_bytes,
            "shape": shape,
            "scale": scale,
            "bit_width": bit_width,
            "quant_scheme": quant_scheme
        }
        self.weight_metadata[name] = meta
        return meta

    def convert(self, sample_input: "torch.Tensor" = None) -> str:
        traced = fx.symbolic_trace(self.model)
        graph = traced.graph

        self.mlir_lines.append("// Generated by Tenzo PyTorch FX Frontend (Zero-Copy Bridge)")
        self.mlir_lines.append("module {")

        # 1. Inspect parameters & submodules
        for name, param in self.model.named_parameters():
            is_bitlinear = False
            # Check if this weight belongs to a BitLinear module
            parent_module_name = name.rsplit(".", 1)[0] if "." in name else ""
            if parent_module_name:
                mod = dict(self.model.named_modules()).get(parent_module_name)
                if isinstance(mod, BitLinear):
                    is_bitlinear = True

            meta = self._save_weight(name, param, is_ternary=is_bitlinear)
            
            shape_str = "x".join(map(str, meta["shape"]))
            memref_type = f"memref<{shape_str}xf32>"
            clean_name = name.replace(".", "_")
            
            decl = (f'  memref.global "public" constant @{clean_name} : {memref_type} = '
                    f'dense<0.0> {{offset = {meta["offset"]} : i64, size_bytes = {meta["size_bytes"]} : i64, '
                    f'bit_width = {meta["bit_width"]} : i32, quant_scheme = "{meta["quant_scheme"]}"}}')
            self.mlir_lines.append(decl)

        self.mlir_lines.append("")

        # 2. Main function creation
        input_args = []
        input_types = []
        arg_idx = 0

        for node in graph.nodes:
            if node.op == "placeholder":
                shape_str = "1x10"  # Default fallback if sample input shape not known
                if sample_input is not None:
                    shape_str = "x".join(map(str, list(sample_input.shape)))
                
                t_type = f"tensor<{shape_str}xf32>"
                ssa_name = f"%arg{arg_idx}"
                arg_idx += 1
                input_args.append(f"{ssa_name}: {t_type}")
                input_types.append(t_type)
                self.ssa_map[node] = ssa_name
                self.type_map[ssa_name] = t_type

        # Output signature placeholder
        out_type = input_types[0] if input_types else "tensor<1x2xf32>"
        func_sig = f"  func.func @main({', '.join(input_args)}) -> ({out_type}) {{"
        self.mlir_lines.append(func_sig)

        # 3. Process FX Graph nodes
        for node in graph.nodes:
            if node.op in ("placeholder", "get_attr"):
                continue

            elif node.op == "call_module":
                submod = dict(self.model.named_modules()).get(node.target)
                if isinstance(submod, BitLinear):
                    inp = self.ssa_map[node.args[0]]
                    inp_type = self.type_map[inp]
                    
                    # Weight global reference
                    w_name = f"{node.target}.weight".replace(".", "_")
                    w_shape = list(submod.weight.shape)
                    w_shape_str = "x".join(map(str, w_shape))
                    w_memref_type = f"memref<{w_shape_str}xf32>"
                    w_tensor_type = f"tensor<{w_shape_str}xf32>"
                    
                    w_memref_var = self._get_new_var(w_memref_type)
                    self.mlir_lines.append(f'    {w_memref_var} = memref.get_global @{w_name} : {w_memref_type}')
                    
                    w_tensor_var = self._get_new_var(w_tensor_type)
                    self.mlir_lines.append(f'    {w_tensor_var} = bufferization.to_tensor {w_memref_var} : {w_memref_type} to {w_tensor_type}')
                    
                    # 1. Quantize Op
                    q_var = self._get_new_var(w_tensor_type)
                    self.mlir_lines.append(
                        f'    {q_var} = "tenzo.quantize"({w_tensor_var}) {{bit_width = 2 : i32, quant_scheme = "ternary"}} : '
                        f'({w_tensor_type}) -> {w_tensor_type}'
                    )

                    # 2. MatMul Op
                    out_shape = [1, w_shape[0]]  # [Batch, OutFeatures]
                    out_shape_str = "x".join(map(str, out_shape))
                    mm_type = f"tensor<{out_shape_str}xf32>"
                    mm_var = self._get_new_var(mm_type)

                    self.mlir_lines.append(
                        f'    {mm_var} = "tenzo.matmul"({inp}, {q_var}) : ({inp_type}, {w_tensor_type}) -> {mm_type}'
                    )

                    # 3. Optional Bias Add
                    if submod.bias is not None:
                        b_name = f"{node.target}.bias".replace(".", "_")
                        b_shape = list(submod.bias.shape)
                        b_shape_str = "x".join(map(str, b_shape))
                        b_memref_type = f"memref<{b_shape_str}xf32>"
                        b_tensor_type = f"tensor<{b_shape_str}xf32>"
                        
                        b_memref_var = self._get_new_var(b_memref_type)
                        self.mlir_lines.append(f'    {b_memref_var} = memref.get_global @{b_name} : {b_memref_type}')
                        b_tensor_var = self._get_new_var(b_tensor_type)
                        self.mlir_lines.append(f'    {b_tensor_var} = bufferization.to_tensor {b_memref_var} : {b_memref_type} to {b_tensor_type}')
                        
                        add_var = self._get_new_var(mm_type)
                        self.mlir_lines.append(
                            f'    {add_var} = "tenzo.add"({mm_var}, {b_tensor_var}) : ({mm_type}, {b_tensor_type}) -> {mm_type}'
                        )
                        self.ssa_map[node] = add_var
                    else:
                        self.ssa_map[node] = mm_var

            elif node.op == "call_function":
                target = node.target
                if target in (torch.relu, F.relu):
                    inp = self.ssa_map[node.args[0]]
                    inp_type = self.type_map[inp]
                    res_var = self._get_new_var(inp_type)
                    self.mlir_lines.append(f'    {res_var} = "tenzo.relu"({inp}) : ({inp_type}) -> {inp_type}')
                    self.ssa_map[node] = res_var

                elif target in (torch.add,):
                    lhs = self.ssa_map[node.args[0]]
                    rhs = self.ssa_map[node.args[1]]
                    inp_type = self.type_map[lhs]
                    res_var = self._get_new_var(inp_type)
                    self.mlir_lines.append(f'    {res_var} = "tenzo.add"({lhs}, {rhs}) : ({inp_type}, {inp_type}) -> {inp_type}')
                    self.ssa_map[node] = res_var

            elif node.op == "output":
                res_val = self.ssa_map[node.args[0]]
                res_type = self.type_map[res_val]
                self.mlir_lines.append(f'    return {res_val} : {res_type}')

        self.mlir_lines.append("  }")
        self.mlir_lines.append("}")

        self.weights_file.close()
        
        mlir_content = "\n".join(self.mlir_lines)
        mlir_out_path = os.path.join(self.output_dir, "model.mlir")
        with open(mlir_out_path, "w") as f:
            f.write(mlir_content)

        print(f"[FX-to-MLIR] Successfully exported model to {mlir_out_path}")
        print(f"[FX-to-MLIR] Binary weights saved to {self.weights_bin_path} ({self.current_byte_offset} bytes)")
        return mlir_content


def export_torch_model_to_tenzo(model: "torch.nn.Module", sample_input: "torch.Tensor", output_dir: str = "."):
    emitter = FXToMLIREmitter(model, output_dir=output_dir)
    return emitter.convert(sample_input=sample_input)


if __name__ == "__main__":
    out_dir = os.path.join(os.path.dirname(__file__), "export_output")
    os.makedirs(out_dir, exist_ok=True)
    bin_path = os.path.join(out_dir, "weights.bin")
    mlir_path = os.path.join(out_dir, "model.mlir")

    if HAS_TORCH:
        from qat import BitLinear

        class TestFXModel(nn.Module):
            def __init__(self):
                super().__init__()
                self.fc1 = BitLinear(10, 20)
                self.relu = nn.ReLU()
                self.fc2 = BitLinear(20, 2)

            def forward(self, x):
                x = self.fc1(x)
                x = self.relu(x)
                x = self.fc2(x)
                return x

        model = TestFXModel()
        sample_input = torch.randn(1, 10)
        export_torch_model_to_tenzo(model, sample_input, output_dir=out_dir)
    else:
        print("[FX-to-MLIR] PyTorch not detected. Running Standalone Pure-Python Mock Exporter...")
        
        # 1. Generate packed weights (128->64 -> 10)
        dummy_weights = [1, -1, 0, 1] * 64
        packed_bytes = pack_ternary_list(dummy_weights)
        
        with open(bin_path, "wb") as f:
            f.write(packed_bytes)

        # 2. Generate model.mlir
        mlir_content = """// Standalone Mock MLIR model for Zero-Copy Bridge Test
module {
  memref.global "public" constant @fc1_weight : memref<20x10xf32> = dense<0.0> {bit_width = 2 : i32, offset = 0 : i64, quant_scheme = "ternary", size_bytes = 64 : i64}

  func.func @main(%arg0: tensor<1x10xf32>) -> tensor<1x20xf32> {
    %0 = memref.get_global @fc1_weight : memref<20x10xf32>
    %1 = bufferization.to_tensor %0 : memref<20x10xf32> to tensor<20x10xf32>
    %2 = "tenzo.quantize"(%1) {bit_width = 2 : i32, quant_scheme = "ternary"} : (tensor<20x10xf32>) -> tensor<20x10xf32>
    %3 = "tenzo.matmul"(%arg0, %2) : (tensor<1x10xf32>, tensor<20x10xf32>) -> tensor<1x20xf32>
    return %3 : tensor<1x20xf32>
  }
}
"""
        with open(mlir_path, "w") as f:
            f.write(mlir_content)

        print(f"[FX-to-MLIR] Successfully generated mock model at {mlir_path}")
        print(f"[FX-to-MLIR] Binary weights saved to {bin_path} ({len(packed_bytes)} bytes)")

