import onnx
import sys
import os
import argparse
from onnx import numpy_helper, shape_inference
import numpy as np

# Add current directory to path to import weight_utils
sys.path.append(os.path.dirname(os.path.abspath(__file__)))
from weight_utils import save_initializer_as_bin, get_mlir_type, get_memref_type

def onnx_to_mlir(onnx_path, output_mlir_path):
    model = onnx.load(onnx_path)
    onnx.checker.check_model(model)
    model = shape_inference.infer_shapes(model)
    graph = model.graph
    
    output_dir = os.path.dirname(os.path.abspath(output_mlir_path))
    weights_dir = os.path.join(output_dir, "weights")
    os.makedirs(weights_dir, exist_ok=True)
    
    mlir_lines = []
    mlir_lines.append("// Generated by Tenzo ONNX Frontend")
    mlir_lines.append("module {")
    
    type_map = {}
    ssa_map = {}
    initializers_info = {}
    
    # 1. Process Initializers (Weights)
    for init in graph.initializer:
        name, decl, bin_path = save_initializer_as_bin(init, weights_dir)
        initializers_info[init.name] = {
            "name": name,
            "shape": list(init.dims),
            "mlir_name": f"@{name}"
        }
        mlir_lines.append(decl)
    
    mlir_lines.append("")
    
    # 2. Function Signature
    inputs = []
    input_types = []
    init_names = {init.name for init in graph.initializer}
    graph_inputs = [i for i in graph.input if i.name not in init_names]
    
    for i, inp in enumerate(graph_inputs):
        shape = []
        for dim in inp.type.tensor_type.shape.dim:
            if dim.HasField("dim_value"):
                shape.append(dim.dim_value if dim.dim_value > 0 else -1)
            else:
                shape.append(-1) # Dynamic
        mlir_type = get_mlir_type(inp.type.tensor_type.elem_type, shape)
        ssa_name = f"%arg{i}"
        inputs.append(f"{ssa_name}: {mlir_type}")
        input_types.append(mlir_type)
        ssa_map[inp.name] = ssa_name
        type_map[ssa_name] = mlir_type

    outputs = []
    output_types = []
    for out in graph.output:
        shape = []
        for dim in out.type.tensor_type.shape.dim:
            if dim.HasField("dim_value"):
                shape.append(dim.dim_value if dim.dim_value > 0 else -1)
            else:
                shape.append(-1)
        mlir_type = get_mlir_type(out.type.tensor_type.elem_type, shape)
        output_types.append(mlir_type)

    func_sig = f"  func.func @main({', '.join(inputs)}) -> ({', '.join(output_types)}) {{"
    mlir_lines.append(func_sig)
    
    var_idx = len(inputs)
    def get_new_var(v_type=None):
        nonlocal var_idx
        v = f"%v{var_idx}"
        var_idx += 1
        if v_type:
            type_map[v] = v_type
        return v

    def resolve_inputs(node, initializers_info, ssa_map, mlir_lines, get_new_var, type_map):
        node_inputs = []
        for inp_name in node.input:
            if not inp_name: continue
            
            if inp_name in initializers_info:
                info = initializers_info[inp_name]
                global_name = info["mlir_name"]
                m_type = get_memref_type(info["shape"])
                t_type = get_mlir_type(None, info["shape"])
                
                v_memref = get_new_var(m_type)
                mlir_lines.append(f'    {v_memref} = memref.get_global {global_name} : {m_type}')
                
                v_tensor = get_new_var(t_type)
                mlir_lines.append(f'    {v_tensor} = bufferization.to_tensor {v_memref} : {m_type} to {t_type}')
                node_inputs.append(v_tensor)
            elif inp_name in ssa_map:
                node_inputs.append(ssa_map[inp_name])
        return node_inputs

    def get_node_output_type(node, graph):
        out_name = node.output[0]
        for vi in list(graph.value_info) + list(graph.output):
            if vi.name == out_name:
                shape = []
                for dim in vi.type.tensor_type.shape.dim:
                    if dim.HasField("dim_value"):
                        shape.append(dim.dim_value if dim.dim_value > 0 else -1)
                    else:
                        shape.append(-1)
                out_shape = shape
                return get_mlir_type(None, out_shape)
        return "tensor<*xf32>"

    # 3. Process Nodes with simple fusion
    i = 0
    while i < len(graph.node):
        node = graph.node[i]
        op_type = node.op_type
        
        # Check for Add + Relu pattern
        if op_type == "Add" and i + 1 < len(graph.node):
            next_node = graph.node[i+1]
            if next_node.op_type == "Relu" and next_node.input[0] == node.output[0]:
                node_inputs = resolve_inputs(node, initializers_info, ssa_map, mlir_lines, get_new_var, type_map)
                out_name = next_node.output[0]
                out_type = get_node_output_type(next_node, graph)
                res_var = get_new_var(out_type)
                ssa_map[out_name] = res_var
                mlir_lines.append(f'    {res_var} = "tenzo.fused_add_relu"({node_inputs[0]}, {node_inputs[1]}) : ({type_map[node_inputs[0]]}, {type_map[node_inputs[1]]}) -> {out_type}')
                i += 2
                continue
        
        # Gemm + Relu fusion
        node_inputs = resolve_inputs(node, initializers_info, ssa_map, mlir_lines, get_new_var, type_map)
        out_name = node.output[0]
        out_type = get_node_output_type(node, graph)
        
        if op_type == "Gemm" and i + 1 < len(graph.node) and graph.node[i+1].op_type == "Relu" and graph.node[i+1].input[0] == node.output[0]:
            next_node = graph.node[i+1]
            tmp_type = out_type 
            tmp_var = get_new_var(tmp_type)
            mlir_lines.append(f'    {tmp_var} = "tenzo.matmul"({node_inputs[0]}, {node_inputs[1]}) : ({type_map[node_inputs[0]]}, {type_map[node_inputs[1]]}) -> {tmp_type}')
            
            out_name = next_node.output[0]
            out_type = get_node_output_type(next_node, graph)
            res_var = get_new_var(out_type)
            ssa_map[out_name] = res_var
            mlir_lines.append(f'    {res_var} = "tenzo.fused_add_relu"({tmp_var}, {node_inputs[2]}) : ({tmp_type}, {type_map[node_inputs[2]]}) -> {out_type}')
            i += 2
            continue

        res_var = get_new_var(out_type)
        ssa_map[out_name] = res_var

        if op_type == "MatMul":
            mlir_lines.append(f'    {res_var} = "tenzo.matmul"({node_inputs[0]}, {node_inputs[1]}) : ({type_map[node_inputs[0]]}, {type_map[node_inputs[1]]}) -> {out_type}')
        elif op_type == "Relu":
            mlir_lines.append(f'    {res_var} = "tenzo.relu"({node_inputs[0]}) : ({type_map[node_inputs[0]]}) -> {out_type}')
        elif op_type == "Add":
            mlir_lines.append(f'    {res_var} = "tenzo.add"({node_inputs[0]}, {node_inputs[1]}) : ({type_map[node_inputs[0]]}, {type_map[node_inputs[1]]}) -> {out_type}')
        elif op_type == "Gemm":
            tmp_type = out_type
            tmp_var = get_new_var(tmp_type)
            mlir_lines.append(f'    {tmp_var} = "tenzo.matmul"({node_inputs[0]}, {node_inputs[1]}) : ({type_map[node_inputs[0]]}, {type_map[node_inputs[1]]}) -> {tmp_type}')
            mlir_lines.append(f'    {res_var} = "tenzo.add"({tmp_var}, {node_inputs[2]}) : ({tmp_type}, {type_map[node_inputs[2]]}) -> {out_type}')
        elif op_type == "Conv":
            mlir_lines.append(f'    {res_var} = "tenzo.conv2d"({node_inputs[0]}, {node_inputs[1]}) : ({type_map[node_inputs[0]]}, {type_map[node_inputs[1]]}) -> {out_type}')
        else:
            mlir_lines.append(f'    // Unsupported op: {op_type}')
            mlir_lines.append(f'    {res_var} = "tenzo.unsupported"() : () -> {out_type}')
        
        i += 1

    # Return
    final_outputs = [ssa_map[out.name] for out in graph.output]
    mlir_lines.append(f'    return {", ".join(final_outputs)} : {", ".join(output_types)}')
    mlir_lines.append("  }")
    mlir_lines.append("}")
    
    with open(output_mlir_path, 'w') as f:
        f.write("\n".join(mlir_lines))
    print(f"Successfully converted {onnx_path} to {output_mlir_path}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Convert ONNX to Tenzo MLIR')
    parser.add_argument('input', help='Input ONNX model')
    parser.add_argument('-o', '--output', help='Output MLIR file', default='output.mlir')
    args = parser.parse_args()
    
    onnx_to_mlir(args.input, args.output)
